### ISSUE TITLE
List of snippets

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#1]
## Value proposition
As an efficiency-driven web-developer
I want to see a list of (sample-) snippets on the app's home-page
In order to get an overview of existing snippets.
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] The page should render a list 
- [ ] 
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team

**Comment by NikRoe** [comment]
Hi there,

very well done! 👏 

I will already approve it, since there is only minor thing I would change:

> In SnippetCard.js write an if/else statement so that if there is no data the text "No snippets yet" is displayed

You don't need to be that explicit about how you will implement the logic.
Simply mentioning that you will add logic to handle this case would have sufficed.
