### ISSUE TITLE
Bookmark snippet(s) as favorite (on overview and detail view page)

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#10]
## Value proposition
As a user
I want to bookmark my favorite snippets
In order to have all my favorite snippets collected in one place.
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/3725208d-1fea-4813-a886-b2e751735593)

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/0ab8288f-9f7a-45ea-934b-ce5db3c73881)

![image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/f488f8cc-6ce9-49ad-a30b-a6e2dcbb894d)

## Acceptance criteria
- [x] each snippet can be marked and unmark as favorite on the overview, the details and favorite page
- [x] favorite page shows the headline "my favorites"
- [x] button shows a star icon that changes it's appearance when marked or unmarked as favorite - on the overview, the details and favorite page
- [x] favorite page lists all snippets that have been marked as favorite
- [x] footer includes link to favorite page
- [x] favorite page includes a "go back" link
## Tasks
- [x] create a new branch feat/bookmark
- [x] create a bookmark component to use it on the overviewPage, the detailsPage and the favorite page
- [x] create bookmark functionality with useState
- [x] implement the "go back" link on the favorite page
- [x] render a headline "my favorites" on the favorites page
- [x] render all favorites on favorite page with mapping over all snippets
- [x] add link to favorites-page to the footer

**Comment by FelineHuhn** [comment]
Nice feature 🙌 First I was confused about the web-developer in your value proposition, but I think the user of your app is a web developer, right? 

To you value proposition: Maybe you could expand the purpose of the US like "in order to have all my favorite snippets collected in one place". That's of course a matter of taste, what do you think?

I think the acceptance criteria could be a little more precise. E.g. better write "each snippet can be marked and unmark as favorite". You could mention that the button shows a star icon that changes it's appearance when marked or unmarked as favorite. If you want to be precise you should mention the headline of the new favorites page and also, that the header is also displayed there (in your acceptance criteria but also as tasks, since you have to add the appropriate components to the favorites page, or?) .

**Comment by doemser** [comment]
Looks Good.

You could elaborate on how the appearance of the star icon should change, but thats just nice-to-have.

Approved.
