### ISSUE TITLE
Copy code snippet with one click

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#13]
## Value proposition
As a user
I want to copy the code snippet with one click
In order to safe time, be more efficient and work convenient. 
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/df30264d-46d3-4f96-8549-218950dfda72)

## Acceptance criteria
- [ ] on the overview page a copy-icon is rendered on each card in the right corner
- [ ] after clicking the copy-icon it copies the whole code and changes the appearence into a checkmark
- [ ] a copy-icon is rendered on the detail page in the right corner of the code box
- [ ] clicking the copy-icon copies the whole code and changes the appearence into a checkmark and the message "code copied "
- [ ] the message "code copied"/ the checkmark (on the overview page) will reset after a timer of 3sec.
## Tasks
- [ ] create a new branch feat/copy-with-one-click
- [ ] create a "CopyWithOneClick" component to use it on the overview page and the detail page
- [ ] use navigator.clipboard.writeText()-API to implement the copy functionality (https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText)
- [ ] implement an aria-label="code copied "

**Comment by doemser** [comment]
looks good, but please refine what happens after someone copied the button.

**Comment by fel-sad** [comment]
looks good to me now 😄
