### ISSUE TITLE
Implement better usability for guides

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#14]
## Value proposition
As a <user/role>
I want to <feature/goal>
In order to store guides and show them so i can easily decide if this was the right one to open.
## Acceptance criteria
- [ ] Embedded preview of the links
- [ ] 
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team
