### ISSUE TITLE
Bonus: Add animation after submitting data

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#16]
## Value proposition
As an efficiency-driven web developer
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] create a new branch
- [ ] List the tasks that need to be performed within the dev team
