### ISSUE TITLE
Adding more than one link

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#17]
## Value proposition
As an efficiency-driven web-developer (aka, the user)
I want to be able to add more than one link when creating a new snippet and/or updating an existing snippet
In order to be able to store multiple internet resources relevant for the given snippet.
## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136967950/44fb5e3e-16a2-403b-bc4b-adb204457517)

## Acceptance criteria
The following holds good both for the page for creating a new snippet and for editing an existing snippet:
- [x] Below the link-field, there is a button with a plus-sign and the text "Add another link".
- [ ] When hovering over the button, the standard mouse pointer changes to a hand-pointer.
- [x] Clicking the button has the following effects:

> - [ ] A further link field appears beneath the original link field.
> - [ ] On the right side of both the original and the newly added link field, there appears a minus sign (which is a button).

- [ ] When hovering over the minus-sign, the standard mouse pointer changes to a hand-pointer.
- [ ] Clicking the minus-sign, removes the relevant link field.
- [ ] If there is only one link-field, there is no possibility to delete it (and, hence, no minus-button).
## Tasks
- [ ] create a new branch feat/add-more-than-one-link
- [x] Within the SnippetForm component, add a button below the link input field.
- [ ] The handler function for the button should create a new link field and delete-buttons.
- [ ] Work with useState in order to update the link collection (probably an array).

**Comment by gregorsart** [comment]
Looks good to me, but maybe show only one Screendesign instead of four in the Description.
