### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#2]
## Value proposition
As a efficiency-driven web-developer 
I want to see on the top of the app the name "/ˈsnɪp.ɪt/" of the app
In order to know which app am I using
## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/62f1c0de-a634-433a-82ac-cf0228bf8cde)

## Acceptance criteria
- [x] the header renders the name  "/ˈsnɪp.ɪt/" of the app
- [x] the header is fixed while scrolling

## Tasks
- [x] create a feature branch
- [x] create a Header component in components/Header.js
- [x] render the Header component in the _app.js
- [x] make the header fixed (styled components)

**Comment by NikRoe** [comment]
Hi there,

does it already provide any value for the user to be redirected to the homepage when clicking on the header? It would seem to me that this only makes sense, once there are several pages.

In your tasks you can remove the point with the CSS positioning. This is an implementation detail that you don't need to mention.

Best regards.
