### ISSUE TITLE
Database for tags

### ISSUE THREAD

**Issue by NadjaKanunnikow** [PeetThesing/capstone-project_snippet-manager#25]
## Value proposition
As an efficiency-driven web developer
I want to be able to add my own tags 
In order to sort my collection according to my own preferences
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] create a new branch
- [ ] List the tasks that need to be performed within the dev team
