### ISSUE TITLE
Accessibility best practice according to WCAG 

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#26]
- WCAG 
- Schriftgröße, dass Bildschirm nicht horizontal gescrollt werden muss wenn man reinzoomt (bis 200 Prozent min, gerne mehr)
- Navigation nutzbar
- Knöpfe sind ein Problem, Buttons beim Formular müssen acceissble sein
- Keine Überlappungen
- Aria-Label
- Smilie Probleme?

Success Criterion 1.4.8 Visual Presentation
    Foreground and background colors can be selected by the user.
    Width is no more than 80 characters or glyphs
    Text is not justified (aligned to both the left and the right margins).
    Line spacing (leading) is at least space-and-a-half within paragraphs, and paragraph spacing is at least 1.5 times larger than the line spacing.
    Text can be resized without assistive technology up to 200 percent in a way that does not require the user to scroll horizontally to read a line of text [on a full-screen window](https://www.w3.org/TR/WCAG21/#dfn-on-a-full-screen-window).

Success Criterion 1.4.10 Reflow
Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:

    Vertical scrolling content at a width equivalent to 320 [CSS pixels](https://www.w3.org/TR/WCAG21/#dfn-css-pixels);
    Horizontal scrolling content at a height equivalent to 256 [CSS pixels](https://www.w3.org/TR/WCAG21/#dfn-css-pixels).

Success Criterion 1.4.12 Text Spacing

In content implemented using markup languages that support the following [text](https://www.w3.org/TR/WCAG21/#dfn-text) [style properties](https://www.w3.org/TR/WCAG21/#dfn-style-properties), no loss of content or functionality occurs by setting all of the following and by changing no other style property:

    Line height (line spacing) to at least 1.5 times the font size;
    Spacing following paragraphs to at least 2 times the font size;
    Letter spacing (tracking) to at least 0.12 times the font size;
    Word spacing to at least 0.16 times the font size.

## Value proposition
As an efficiency-driven web developer
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] create a new branch
- [ ] List the tasks that need to be performed within the dev team
