### ISSUE TITLE
Style everything responsive, accessible and fun to use

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#29]
## Value proposition
As an aesthetic oriented web developer (a.k.a. the user)
I want to interact with an intuitive, accessible, and enjoyable interface
In order to efficiently complete my tasks and enjoy the process

## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/732e4d5c-bb86-4a0c-b005-fc78621e3c40)
## Acceptance criteria
Form page
- [x] The required form field is clearly visible via "name*" and "code*"
- [x] If the user tries to send the form without the required fields, it changes the color of the border to red and shows the message "This field is required"
- [x] The success / error message includes a big emoji
Edit page:
- [x] The edit link looks like a button, same as update
Details View:
- [x] The code part has syntax highlighting
- [x] The back link looks like a button

## Tasks
- [x] create a new branch
- [x] create a global color variable for text (use #04151B) and for the form fields (use #C1D2D7)
- [x] add a symbol (*) to the required Form fields (name & code)
- [x] add a message on the required fields if the user tries to send the form without it & highlight the required field as shown in the wireframe
- [x] style the fields in the EDIT/ADD NEW Form, add a border radius
- [x] create a button component for all buttons (Update, Delete, Reset)
- [x] create a component for the Edit- Link
- [x] create a card for the details page 
- [x] style the back-Link component
- [x] install and configure a syntax highlighting library

**Comment by julialoeschel** [comment]
Hey, 

I do have some remarks on this one: 
- your VP is from developers view. Why? your costumer is the user and that person needs a styled app. make sure you are  focusing on the user.
- delete the text in the description. Its an overall very vague text. If you have a scribble, it should represent all the content of the US, if you have to write something - be percise.
- be clear in your AC
e.g. "If the user tries to send the form without the required fields, it changes the color **to red border** and shows the message "This field is required" "
" The overall appearance of the app is unified and a pleasure to look at" - is very vague.
"Everything that has to look like a button, looks like it" how does the button look like? 

is the Design ready? if yes, show it. If no, this US shall not pass. 
If you want to work on the desgin in this US, make sure someone could work on it, that just joined your team without asking you. provide the layout and design of every page.

same with the tasks: 

- "add a symbol (*) or text "required" to the required Form fields" - why **or**?  if you are not sure jet, dont get this story to review. 
- " create the same button-like appearance for the [✏️ Edit] Link" -  please provide the design
- ...


I think you know where this is going. 
overall it is a good story and you target the right things. 
But as I read it, it looks to me like there is no design choice jet, and the developer has to figure out on the go.
Please have a design ready when you put this story in review.

**Comment by julialoeschel** [comment]
Oh, I just realized that your user is a web developer, right? 
please make sure not to confuse people(me or any other stakeholder of your project) by not clarifying this ;)

**Comment by doemser** [comment]
You may want to specify which syntax highlighting library to use or at least mention the popular options you are going to research on, in order to complete this story..
