### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#3]
## Value proposition
As an efficiency-driven web-developer 
I want to see a footer on the bottom of the list of snippets (homepage) and detail page
In order to be directed to the form and be able to add new snippets 
## Description
This should be done after list of snippets and details page.
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/f406f70e-4736-4d08-9b4f-fdd246a7ff4d)

## Acceptance criteria
- [ ] the footer renders an add-button, that directs to the form
- [x] the footer is fixed while scrolling
## Tasks
- [x] create a feature branch
- [x] create a Footer component in components/Footer.js
- [x] add a link to the form page
- [x] make the footer fixed (styled components)

**Comment by onemanwenttomow** [comment]
I think in general this ticket is good. **However**, i think this ticket should only be worked on once there is a form and collections page available to link to. 

My suggestion would be to remove the following (otherwise the user will be directed to empty or placeholder pages)

-  create a Footer component in components/Footer.js
-  create pages/form.js and pages/collections.js

And then make sure this user story is only started once these pages exist (i.e. **after** a different user story)

There is a typo in the value proposition. `As a As a efficiency-driven web-developer`.

**Comment by PeetThesing** [comment]
Thank you for your comment. Because we use the footer on different pages, we need a component. At this time, there will be at least to pages (Homepage and Details Page).
