### ISSUE TITLE
Adding more than one tag

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#34]
## Value proposition
As an efficiency-driven web developer (the user)
I want to add more than one tag to each snippet
In order to categorize my content more efficiently.
## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/61c3d6f2-0479-4b8c-8134-55aa27fe8940)
## Acceptance criteria
- [ ] The form should provide a list of predefined tags for the user to select from
- [ ] The user should be able to select multiple tags from the predefined list.
- [ ] The form should allow the user to add custom tags if their desired tag is not in the predefined list.
- [ ] Custom tags added by the user should be saved and displayed alongside the predefined tags.
## Tasks
- [ ] create a new branch
- [ ] Create a multiple selection possibility for the drop down menu
- [ ] Create an option to enter custom tags
- [ ] handle the user input and add it to the tag-array
- [ ] Save the selected tags (both predefined and custom) in the database
- [ ] Implement validation restriction for tag length

**Comment by fel-sad** [comment]
Looks good to me, but I would suggest to make it a bit clearer in the description where the input for custom tags should be. 😄
