### ISSUE TITLE
Confirm Message

### ISSUE THREAD

**Issue by NadjaKanunnikow** [PeetThesing/capstone-project_snippet-manager#35]
## Value proposition
As an efficiency-driven web developer (the user)
I want to be warned before deleting a snippet, 
In order to avoid deleting something by accident. 
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/8c0eb1fb-ab1a-4cd0-8d38-096328dc5b70)

## Acceptance criteria
- [ ] after clicking the "delete"-button on the details page for a snippet a confirm message appears with the text "Are you sure you want to delete the snippet {name of the snippet}" and two buttons, "confirm" and "cancel"
- [ ] after clicking "cancel" the confirm message disappears and the user stays on the details page of the snippet 
- [ ] after clicking "confirm" the snippet is permanently deleted and the user is redirected to the overview page
## Tasks
- [ ] create a new branch feat/confirm-message
- [ ] create a comfirm message Component 
- [ ] use useState to handle the confirm message
