### ISSUE TITLE
Toaster Component

### ISSUE THREAD

**Issue by NadjaKanunnikow** [PeetThesing/capstone-project_snippet-manager#43]

**Comment by PeetThesing** [comment]
## Value proposition
As a user
I want to have success messages as a toaster message
In order to have a nice user experience and continue to work while I get the success message.
## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/6e436150-58bb-4624-b243-f39183d25f1f)
## Acceptance criteria
- [ ] toaster message is visible at the top of the page
- [ ] it appears after an interaction with the page (edting, adding or deleting)
## Tasks
- [ ] Create a new branch
- [ ] import react-hot-toast
- [ ] Create a Component and style the toaster message according to the wireframe
- [ ] implement the Toaster on the SnippetDetailsPage ("Deleted successfully!")
- [ ] implement the Toaster in the SnippetForm ("Added snippet successfully.")
- [ ] implement the Toaster on the EditPage ("Edited snippet successfully.")
