### ISSUE TITLE
refactor syntax highlighting

### ISSUE THREAD

**Issue by NadjaKanunnikow** [PeetThesing/capstone-project_snippet-manager#44]
## Value proposition
As a user
I want to see the code properly without irritating wraps
In order to grasp the sense of the code easily
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/1571181a-5171-4bc0-974f-b99eb0c4b2e4)

## Acceptance criteria
- [ ] the code should not wrap
- [ ] the syntax highlighting depends on the chosen tag
- [ ] its possible to add other languages e. g. python etc. and the syntax highlighter adapts to the programming language 
## Tasks
- [ ] create a new branch feat/syntax-highlighting-advanced
- [ ] make tags field required
- [ ] adapt the attributes for the <StyledSyntaxHighlighter/> component according to the tag and make it conditionally
- [ ] add more languages in form of attributes to the <StyledSyntaxHighlighter/> component in the <SnippetDetails/> component

**Comment by Julia-Pickel** [comment]
Nice and clear user story! 

LGTM 🙌

**Comment by NadjaKanunnikow** [comment]
While working on this feature we realized that the connection to the tags makes no sense anymore, because we can´t connect the language for the syntax highlighter with more than one tag. So we build a dropdown menu in the form component to select the language the syntax highlighter depends on. So the tags are not required.
