### ISSUE TITLE
Improve FormComponent

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#49]
## Value proposition
As a user
I want to have an intuitive, smooth and fun user experience on both pages, "add new" and "edit"
In order to add and edit my desired snippets quickly and efficient.
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/08ca24f8-af7a-444c-b8ff-dc7c1d11ccab)

## Acceptance criteria
- [x] Links should function if they start with https:// as well (at the moment it only works when links start with www. or with the part that comes after the www.).
- [x] The edit-page has a Go-Back-Link.
- [x] The reset-button works.
- [x] Reset-Button on the edit-page should be renamed to Cancel-Button.
- [x] The edit-page's styling corresponds to the add-page's styling regarding to the global colors
## Tasks
- [x] create a new branch feat/improve-form-component
- [x] add the LinkLayout component to the edit-page
- [x] fix the reset-button on in the SnippetForm-component and rename it to "cancel" for the edit-page
- [x] adjust the colors from the "add new"-page to the "edit"-page for the Headline and the whole text
- [x] implement the error-message for required fields as in the "add new"-page

**Comment by nvhsk** [comment]
Looks good 🙌🏼
