### ISSUE TITLE
Details View

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#5]
## Value proposition
As an efficiency-driven developer
I want to have a details view of each code snippet
In order to see the full snippet and gather further information
## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/b0b34250-b7fc-4aa1-b766-5cf04b84728d)
## Acceptance criteria
- [ ] Clicking a snippet-entry redirects to details view
- [ ] The snippet name is displayed.
- [ ] The full code of the snippet is displayed.
- [ ] The snippet description is displayed.
- [ ] The snippet tags are displayed 
- [ ] If available, links to further resources are displayed.
- [ ] Clicking the back-button redirects to the previous page.
- [ ] Clicking on the header should redirect to the homepage
## Tasks
- [ ] Create new feature-branch
- [ ] Create the component SnippetDetails
- [ ] It accepts the props name, code, description, tags, and links.
- [ ] Create the page pages/snippets/[id]
- [ ] Use the id to find the relevant snippet
- [ ] Create the page pages/api/[id].js
- [ ] Write a GET-request that reads data from the DB in accordance with the given id
- [ ] Render the snippet data
- [ ] Create a BackButton component and render it above the SnippetDetails component (both components are rendered within the pages/snippets/[id].js file)
- [ ] Implement logic so that the back-button redirects to the previous page.
- [ ] add a link to the header that redirects to the homepage

**Comment by NikRoe** [comment]
Hi there,

this looks very promising! 

I would remove the footer from the wireframe, since your footer only makes sense once there are several pages with content.

You don't need to mention implementation details such as 
>  Read the id-parameter with next/router
And you can remove it.

Best regards
