### ISSUE TITLE
Improve the Accessibility for the SearchBar

### ISSUE THREAD

**Issue by NadjaKanunnikow** [PeetThesing/capstone-project_snippet-manager#54]
## Value proposition
As a user with accessibility needs
I want to use keyboard navigation
In order to quickly explore my recent search requests
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/210ab2ad-4699-43cf-bc3c-4a7e2be27008)

## Acceptance criteria
- [x] When clicking into the search bar the user is able to go through the history with the arrow keys and select the desired search term with enter
- [ ] after clicking "enter" the search term is moved to the search bar and the live search get triggered and the user can select the results with the tab key
## Tasks
- [ ] create a new branch feat/searchbar-accessibility
- [ ] create a function that handles the keyboard input and navigates through the search history
- [ ] work with the index of the search history array

**Comment by Julia-Pickel** [comment]
Hey _'snippet'_ team ! 🙌 

I like that you want to work on your accessibility! 
The US is very clear, however I have a minor suggestion.

**Value proposition**
As a user with accessibility needs
I want to use keyboard navigation
In order to quickly explore my recent search requests

**Comment by NadjaKanunnikow** [comment]
thanks, that's much better! 🚀

**Comment by Roland-Hufnagel** [comment]
Great 👍
