### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by PeetThesing** [PeetThesing/capstone-project_snippet-manager#55]
## Value proposition
As an user (web-developer)
I want the app to look pleasant for an eye, modern and minimalistic
In order to make a good UX experience & not distract and overwhelm the user with design 

## Description
![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/119431403/94573e81-f67c-4b6c-823f-cf38834abd67)

## Acceptance criteria
- [ ] minimalistic modern design
- [ ] has an accent color/gradient
- [ ] gradient background & white space behind the snipped cards
- [ ] round edges 
- [ ] the whole app looks unified

## Tasks
- [ ] make research for modern good-looking apps
- [ ] choose accent colors 
- [ ] present to the team
- [ ] change/improve if needed
- [ ] create a new branch
- [ ] implement the new CSS on the main page
- [ ] adjust the design on all the pages
- [ ] make sure everything looks unified

**Comment by Roland-Hufnagel** [comment]
Good Userstory. Only one question:
``As an user (web-developer)``  - why (web-developer) ?
