### ISSUE TITLE
Form to Create New Snippet-Entry

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#6]
## Value proposition
As a efficiency-driven developer
I want to enter new data
In order to fill my snippet manager with my own code snippets, guides and helpful links.
## Description

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/ded79ced-cb17-4ab9-8e62-67ea6d3a440f)

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/b5918b52-948a-4ef4-ae6b-24089e018f15)

![Image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/136720547/13eb51a5-b642-4cbc-91da-776d44af1c9a)

## Acceptance criteria
- [ ] Formular with fields for name, code, description, links, tags
- [ ] Heading
- [ ] A submit button
- [ ] a reset button
- [ ] Users can submit the form without entering description, code and/or link fields
- [ ] The snippet list should be updated after submitting the form
- [ ] After submitting, there should be a message: "Successfully added to your collection" or "something went wrong" 

## Tasks
- [x] Create a feature branch
- [x] Create Form component containing "submit" button, "reset" button and input fields for:

> - [x] name and tags (both required)
> - [x] code, description and links (all optional)

- [x] ensure accessibility
- [x] POST data to database
- [x] Render the form in pages/form.js
- [x] After submitting, render success or error message

**Comment by NikRoe** [comment]
Hi there,

nice start!

In the AC I would specify that the snippet list will be updated after submitting the form.

And I was wondering: After submitting and seeing the message, will users stay on that page and can add more snippets or will they be redirected somewhere? (This is not a suggestion, I was only thinking about this)

In your tasks, you don't need to be that specific. They could look like this:
...
> Create Form component containing submit button and input fields for:
> name and tags (both required)
> code, description and links (all optional)
> ensure accessibility
> POST data to database
> Render the form in pages/form.js
...

And I don't think you will need mutate here.

Best regards

**Comment by NikRoe** [comment]
Hi there,

this looks good to me!

I'll approve this US, but please still consider these suggestion:

>  The description, code and link-field shouldn't be required, so that I can just enter a code or a link - and if I am in a hurry don't have to enter a description.

Users can submit the form without entering description, code and/or link fields

That would make the US even more readable.

Best regards 👋
