### ISSUE TITLE
Fix minor issues

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#62]
- [ ] Toaster auf Edit-Seite: Erscheint immer, wenn man auf „Update“ klickt - auch denn, wenn man gar nichts geändert hat
- [ ] NavBar/Footer: Nach einem Seiten-Reload ist stets das Home-Icon gefüllt - auch wenn man gerade gar nicht auf der Home-Seite ist
- [ ] Edit-Page: Wenn man von den obligatorischen Feldern welche nicht ausfüllt und die Warn-Nachricht erscheint, gehen beim updaten die Default-Werte verloren
- [ ] Möglichkeit, Links zu benennen (à la: „Documentation: <Link zur Documentation>; Icon Collection: <Link zur Icon Collection>“
- [ ] Syntaxhighlighter auf Add- und Edit-Page
- [ ] Sinnvolle Snippets
- [ ] README.md
- [ ] Code aufräumen

## Value proposition
As a user
I want to <feature/goal>
In order to <benefit/purpose>
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?
## Tasks
- [ ] create a new branch
- [ ] List the tasks that need to be performed within the dev team
