### ISSUE TITLE
Delete functionality on detail-view-page

### ISSUE THREAD

**Issue by RolandHesse** [PeetThesing/capstone-project_snippet-manager#8]
## Value proposition
As an evolving developer
I want to delete snippets I don't need anymore
In order to tidy up my database.
## Description
![image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/20aaa968-ac10-47c4-80f2-fbf265f9debc)
![image](https://github.com/PeetThesing/capstone-project_snippet-manager/assets/87306048/a96e8330-e17d-45bf-b4c6-d3385fc2dbe9)

## Acceptance criteria
- [x] A delete button is displayed below the code on the details view page
- [ ] A message "Successfully deleted" is displayed
- [x] The button at the top leads back to where you came from
## Tasks
- [x] Create a new branch
- [x] DELETE data in the database
- [x] Render a delete- button in pages/[id].js
- [ ] Render the message after deleting an Entry

**Comment by NikRoe** [comment]
LGTM

What you could think about for upcoming user stories:
- do you want to ask users prior to deleting a snippet if they are certain?
- do you want to redirect users to the homepage and display the confirmation of the deletion as a toast?
